name: Python Build

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string

jobs:
  Python:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: [ubuntu-latest, macOS-latest]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.branch }}

    - uses: actions/checkout@v4
      if: ${{ inputs.branch }}
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      shell: bash
      run: |
        pip install --upgrade hatch

    - name: Run Linting
      run: hatch -v run lint

    - name: Run Build
      run: hatch build

    - name: Run Tests
      run: hatch -v run test
